---
title: "FAB_Retailer_Analysis"
author: "Renjing Liu"
date: "2021/2/4"
output: pdf_document2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Simulate data set
```{r}
library(tidyverse)
library(scales)
set.seed(123)
Table_1<- 
  tibble(person= c(1:392),
         Factor= sample(x= c(1,2,3),
                        size = 392,
                        replace = TRUE,
                        prob = c(0.55, 0.30,0.15)),
         Gender= sample(x=c(1,2),
                        size= 392,
                        prob = c(0.2,0.8),
                        replace = TRUE),
         Age_Group= sample(x=c(1,2,3),
                           size=392,
                           prob=c(0.55,0.45,0.05),
                           replace= TRUE))

Table_1<- Table_1%>%
  mutate(Retailer= sample(
    x=c("Sephora","Watsons","Other"),
    size= 392,
    prob = c(0.56,0.40,0.04),
    replace = TRUE
  ))%>%
  filter(Age_Group %in% c(1,2))

Table_2<- Table_1%>%
  count(Factor)%>%
  mutate(percentage= n/sum(n))
#Plot 
p_1<- 
  ggplot(data = Table_2, aes(x= factor(Factor), y= percentage))+
  geom_col(fill=c("red","blue","green"))+
  theme_minimal()+
  labs(y= "占比",
       title = "选择线下零售护肤店时您更关注哪些因素")+
  scale_x_discrete(labels= c(
    "线下零售体验","柜姐服务及专业度","口碑及知名度"
  ))+
  labs(fill= "年龄段")+
  scale_fill_discrete(labels=c("16~22","22~30"))+
  theme(axis.title.x = element_blank())


p_1
# Pie chart
Table_2$Factor= as.factor(Table_2$Factor)
p_2<- ggplot(data = Table_2, aes(x="",y= percentage, fill= Factor))+
  geom_bar(stat= "identity",width = 1, color= "white")+
  theme_void()+#Remove background, grid, numeric labels. 
  geom_text(label=c("口碑及名气","零售消费体验","柜姐服务"))+
  coord_polar("y")

p_2
  



write.csv(Table_1, here::here("Simulation_1.csv"))



ggsave(here::here("Plot_1_1.jpeg"), plot = p_1, device = "jpeg")
```
